// Code generated by MockGen. DO NOT EDIT.
// Source: 2023_asset_management/domain (interfaces: PreviewLinkGenerator)

// Package domain is a generated GoMock package.
package domain

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPreviewLinkGenerator is a mock of PreviewLinkGenerator interface.
type MockPreviewLinkGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockPreviewLinkGeneratorMockRecorder
}

// MockPreviewLinkGeneratorMockRecorder is the mock recorder for MockPreviewLinkGenerator.
type MockPreviewLinkGeneratorMockRecorder struct {
	mock *MockPreviewLinkGenerator
}

// NewMockPreviewLinkGenerator creates a new mock instance.
func NewMockPreviewLinkGenerator(ctrl *gomock.Controller) *MockPreviewLinkGenerator {
	mock := &MockPreviewLinkGenerator{ctrl: ctrl}
	mock.recorder = &MockPreviewLinkGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPreviewLinkGenerator) EXPECT() *MockPreviewLinkGeneratorMockRecorder {
	return m.recorder
}

// GetLinkByCloudFile mocks base method.
func (m *MockPreviewLinkGenerator) GetLinkByCloudFile(arg0 CloudFile) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLinkByCloudFile", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetLinkByCloudFile indicates an expected call of GetLinkByCloudFile.
func (mr *MockPreviewLinkGeneratorMockRecorder) GetLinkByCloudFile(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLinkByCloudFile", reflect.TypeOf((*MockPreviewLinkGenerator)(nil).GetLinkByCloudFile), arg0)
}
