// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"2023_asset_management/application"
	"2023_asset_management/domain"
	"2023_asset_management/infrastructure/googledrive"
	"2023_asset_management/interface/rest_api"
)

import (
	_ "github.com/google/subcommands"
	_ "github.com/google/wire"
)

// Injectors from di_wire.go:

// InitializeAuthCmd creates an Auth Init Struct. It will error if the Event is staffed with
// a grumpy greeter.
func InitializeDICmd() *DI {
	googleDriver := googledrive.NewGoogleDrive()
	cloudFileStorer := domain.NewGoogleCloudFileStore(googleDriver)
	previewLinkGenerator := domain.NewPreviewLinkGenerate()
	fileStorer := application.NewFileStore(cloudFileStorer, previewLinkGenerator)
	serverInterface := api.NewEchoServer(fileStorer)
	di := NewDI(serverInterface)
	return di
}
