// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"2023_asset_management/interface/rest_api"
)

import (
	_ "github.com/google/subcommands"
)

// Injectors from di_wire.go:

// InitializeAuthCmd creates an Auth Init Struct. It will error if the Event is staffed with
// a grumpy greeter.
func InitializeDICmd() *DI {
	serverInterface := api.NewEchoServer()
	di := NewDI(serverInterface)
	return di
}
